name: .NET Core CI

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
  
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build ./ThreeDPayment.sln --configuration Release
    - name: Test
      run: dotnet test ./ThreeDPayment.sln
    - name: Pack
      run: dotnet pack -c Release --no-build -o ./packages
    - name: Push
      run: dotnet nuget push ./packages/ThreeDPayment.*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
